Usful cmake files from pgrouting
MobilityDB/MobilityDB pull request #27
Opened 2020-09-14 20:46 UTC by cvvergara

Closes #26 
cmake Files from pgRouting repository
pgRouting uses them on the build process, I just brought the ones that I feel will be useful (some might not be but they can be removed later if they are not used)
Yeah, many commits for 7 files, but they have all the history associated with them.

Next steps is to start using them.

2020-09-14 23:02 UTC, dkastl commented
What about squash/rebase the PR to have a cleaner Git log?
It would be enough to say "Adds Cmake files from pgRouting" rather than having lots of commits from the original Git history.

2020-09-15 00:14 UTC, cvvergara commented
I don't know I would need to check that the names are not lost on the squah

2020-09-15 01:10 UTC, dkastl commented
Well, on the other hand, do you really think that so many people have significantly contributed to these Cmake files? Or have they been part of the commit because other files were part of the commit? I'm not sure either.

2020-09-15 13:51 UTC, cvvergara commented
Reduced the number of commits, we lost the history,
So thanks to Steve, Anton, Daniel and some others that participated on this files :-)

2020-09-16 01:40 UTC, dkastl commented
... or lookup the file history in the pgRouting project, where everything is still present.

2020-09-16 15:21 UTC, estebanzimanyi requested changes

2020-09-16 15:21 UTC, estebanzimanyi commented on cmake/mdb/Version.cmake
> +    message(STATUS "PGROUTING_VERSION_PATCH: ${PGROUTING_VERSION_PATCH}")
Please change all PGROUTING_ by MOBILITYDB_

2020-09-16 15:52 UTC, estebanzimanyi approved these changes

2020-09-16 15:52 UTC, cvvergara commented
Because I used perl I didnt format to the current .editor config

2020-09-16 15:52 UTC, merged