Add quadSpan function
MobilityDB/MobilityDB pull request #305
Opened 2023-04-03 17:06 UTC by estebanzimanyi

2023-04-03 17:29 UTC, mschoema commented on .github/workflows/windows.yml
What is the purpose of this file, is it supposed to add a new test case for windows?
If so, something is going wrong, as there is no new test added to the list.

2023-04-03 19:58 UTC, mschoema requested changes

2023-04-03 19:58 UTC, mschoema commented on meos/src/point/stbox.c
> +  STBox *result = palloc(sizeof(STBox) * *count);
This probably requires some additional parenthesis around `*count`

2023-04-03 22:08 UTC, estebanzimanyi commented
________________________________
From: Maxime Schoemans ***@***.***>
Sent: Monday, April 3, 2023 9:58:29 PM
To: MobilityDB/MobilityDB ***@***.***>
Cc: ZIMANYI Esteban ***@***.***>; Author ***@***.***>
Subject: Re: [MobilityDB/MobilityDB] Add quadSpan function (PR #305)


@mschoema requested changes on this pull request.

________________________________

In meos/src/point/stbox.c<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMobilityDB%2FMobilityDB%2Fpull%2F305%23discussion_r1156400339&data=05%7C01%7Cesteban.zimanyi%40ulb.be%7C4150568ed59b4f47170208db347dcd8a%7C30a5145e75bd4212bb028ff9c0ea4ae9%7C0%7C0%7C638161487147964792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EUtPbITzdvTXJ0PJka%2BVT0xXaXl90dRYp3LUlgvR7Xo%3D&reserved=0>:

>  {
   ensure_has_X_stbox(box);
   bool hasz = MOBDB_FLAGS_GET_Z(box->flags);
   bool hast = MOBDB_FLAGS_GET_T(box->flags);
   bool geodetic = MOBDB_FLAGS_GET_GEODETIC(box->flags);
   Span *period = hast ? (Span *) &box->period : NULL;
-  int count = hasz ? 8 : 4;
-  STBox *result = palloc(sizeof(STBox) * count);
+  *count = hasz ? 8 : 4;
+  STBox *result = palloc(sizeof(STBox) * *count);


This probably requires some additional parenthesis around *count

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMobilityDB%2FMobilityDB%2Fpull%2F305%23pullrequestreview-1369714492&data=05%7C01%7Cesteban.zimanyi%40ulb.be%7C4150568ed59b4f47170208db347dcd8a%7C30a5145e75bd4212bb028ff9c0ea4ae9%7C0%7C0%7C638161487147964792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NSVfm0hOhMEHriuiiSEpSINh8uWcH5GI2qxVq9US5RE%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGNHMBR2XJJZF7NI6WIYNLDW7MTWLANCNFSM6AAAAAAWRTCOUA&data=05%7C01%7Cesteban.zimanyi%40ulb.be%7C4150568ed59b4f47170208db347dcd8a%7C30a5145e75bd4212bb028ff9c0ea4ae9%7C0%7C0%7C638161487147964792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=31PtFVZASAEhg5lg1hy7uHQGdFLgbCz8glyESw1%2B9BA%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-04 01:34 UTC, mschoema approved these changes

2023-04-04 01:35 UTC, merged